# Google Search Automation Configuration
# 配置檔案用於管理 Google 搜尋自動化系統的各種參數

# 基本設定
general:
  # 最大搜尋頁數
  max_pages: 10

  # 等待超時時間（秒）
  wait_timeout: 15

  # 任務間延遲時間（秒）- 模擬真人使用間隔
  min_delay: 3
  max_delay: 8

  # 目標頁面停留時間範圍（秒）- 模擬真人閱讀時間
  page_delay:
    min: 30
    max: 60

  # 重試次數
  retry_attempts: 3

  # 並發控制
  max_concurrent_searches: 1

  # 隨機執行設定
  random_execution:
    enabled: true
    total_iterations: 500 # 總執行次數
    random_keyword_selection: true # 隨機選擇關鍵字
    random_url_selection: true # 隨機選擇目標網址
    min_delay_between_iterations: 10 # 每次執行間最小延遲（秒）- 增加以避免被偵測
    max_delay_between_iterations: 30 # 每次執行間最大延遲（秒）- 模擬真人使用間隔

# 搜尋關鍵字設定
keywords:
  # 單一關鍵字列表
  single_keywords:
    - keyword: "花蓮 太陽能鋼構"
      enabled: true
      priority: 1
      max_pages: 10
      search_modifiers: []

    - keyword: "花蓮鋼構"
      enabled: true
      priority: 1
      max_pages: 10
      search_modifiers: []

    - keyword: "花蓮 鐵皮屋"
      enabled: true
      priority: 2
      max_pages: 15
      search_modifiers: []

    - keyword: "花蓮鐵工"
      enabled: true
      priority: 2
      max_pages: 15
      search_modifiers: []

    - keyword: "花蓮鐵皮屋"
      enabled: true
      priority: 3
      max_pages: 20
      search_modifiers: []

  # 關鍵字組合
  combinations:
    - keyword: "花蓮 鋼構"
      enabled: true
      priority: 2
      max_pages: 15
      search_modifiers: []

# 目標網址設定
target_urls:
  - url: ".*yksc.*"
    enabled: true
    priority: 1
    match_type: "regex"
    max_attempts: 3

# 瀏覽器設定
browser:
  # Chrome 選項
  options:
    - "--no-sandbox"
    - "--disable-dev-shm-usage"
    - "--disable-blink-features=AutomationControlled"
    - "--disable-extensions"
    - "--disable-plugins"
    - "--disable-images" # 可選：禁用圖片載入以提高速度

  # 視窗大小
  window_size:
    width: 1920
    height: 1080

  # 使用者代理
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# 日誌設定
logging:
  # 日誌等級
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL

  # 日誌檔案
  file: "logs/automation.log"

  # 日誌格式
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # 最大檔案大小（MB）
  max_file_size: 10

  # 保留的日誌檔案數量
  backup_count: 5

  # 控制台輸出
  console_output: true

# 統計和監控設定
monitoring:
  # 統計收集間隔（秒）
  collection_interval: 60

  # 效能報告間隔（秒）
  report_interval: 300

  # 統計檔案
  stats_file: "logs/statistics.json"

  # 詳細統計
  detailed_stats: true

# 錯誤處理設定
error_handling:
  # 錯誤重試次數
  max_retries: 3

  # 重試延遲（秒）
  retry_delay: 5

  # 錯誤報告
  error_reporting: true

  # 錯誤報告檔案
  error_file: "logs/errors.log"

  # 致命錯誤時停止
  stop_on_critical_error: false

# 搜尋策略設定
search_strategy:
  # 搜尋模式
  mode: "sequential" # sequential, parallel, priority

  # 頁面載入等待策略
  page_load_strategy: "intelligent" # intelligent, fixed, dynamic

  # 元素等待策略
  element_wait_strategy: "exponential_backoff" # fixed, exponential_backoff, linear

  # 人性化行為
  human_like_behavior:
    enabled: true
    typing_delay_range: [0.05, 0.15] # 打字延遲範圍（秒）
    mouse_movement: true
    random_scrolling: true

# 效能優化設定
performance:
  # 記憶體管理
  memory_management:
    clear_cache_interval: 100 # 每100次搜尋清理快取
    max_memory_usage: 512 # 最大記憶體使用量（MB）

  # 連線管理
  connection:
    keep_alive: true
    timeout: 30
    max_retries: 3

  # 資源限制
  resource_limits:
    max_cpu_usage: 80 # 最大CPU使用率（%）
    max_memory_usage: 80 # 最大記憶體使用率（%）

# 安全設定
security:
  # 請求間隔（秒）
  request_interval: [2, 5]

  # 每日搜尋限制
  daily_search_limit: 1000

  # IP 輪換（如果有多個代理）
  ip_rotation: false

  # 代理設定
  proxy:
    enabled: false
    http: ""
    https: ""

# 通知設定
notifications:
  # 啟用通知
  enabled: false

  # 通知類型
  types:
    - "email"
    - "slack"

  # 通知條件
  conditions:
    success_rate_threshold: 0.8
    error_rate_threshold: 0.2
    daily_limit_reached: true

  # 電子郵件設定
  email:
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    to_addresses: []

  # Slack 設定
  slack:
    webhook_url: ""
    channel: "#seo-automation"
